package com.example.order.dao;

import com.example.order.entity.TcommCustomer;
import com.example.order.entity.TcommCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcommCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int countByExample(TcommCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int deleteByExample(TcommCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int insert(TcommCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int insertSelective(TcommCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    List<TcommCustomer> selectByExample(TcommCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    TcommCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") TcommCustomer record, @Param("example") TcommCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int updateByExample(@Param("record") TcommCustomer record, @Param("example") TcommCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int updateByPrimaryKeySelective(TcommCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcomm_customer
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    int updateByPrimaryKey(TcommCustomer record);
}