package com.example.order.entity;

import java.util.Date;

public class TcommCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.id_
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.bss_cust_id
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String bssCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.certificate_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String certificateAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.certificate_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.certificate_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String certificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.province_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.province_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.eparchy_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String eparchyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.eparchy_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String eparchyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.area_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.area_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.city_id
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.city
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.org
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private Integer org;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_contact
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.contact_tel
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.contact_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String contactAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_manager
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.create_time
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.creator
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.memo_
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.staff_size
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String staffSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_size
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_class_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custClassType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_class_type_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custClassTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_level
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_level_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custLevelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_state
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_manager_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custManagerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_manager_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custManagerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_manager_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custManagerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.cust_namager_tel
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String custNamagerTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.frist_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String fristPvCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.frist_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String fristPvCallingTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.second_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String secondPvCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.second_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String secondPvCallingTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.third_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String thirdPvCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.third_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String thirdPvCallingTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.four_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String fourPvCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.four_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String fourPvCallingTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.develop_flag
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String developFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.develop_flag_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String developFlagDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.department_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.department_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.frist_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String fristCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.frist_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String fristCallingTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.second_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String secondCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.second_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String secondCallingTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.third_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String thirdCallingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcomm_customer.third_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    private String thirdCallingTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.id_
     *
     * @return the value of tcomm_customer.id_
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.id_
     *
     * @param id the value for tcomm_customer.id_
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.bss_cust_id
     *
     * @return the value of tcomm_customer.bss_cust_id
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getBssCustId() {
        return bssCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.bss_cust_id
     *
     * @param bssCustId the value for tcomm_customer.bss_cust_id
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setBssCustId(String bssCustId) {
        this.bssCustId = bssCustId == null ? null : bssCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.certificate_addr
     *
     * @return the value of tcomm_customer.certificate_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCertificateAddr() {
        return certificateAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.certificate_addr
     *
     * @param certificateAddr the value for tcomm_customer.certificate_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCertificateAddr(String certificateAddr) {
        this.certificateAddr = certificateAddr == null ? null : certificateAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.certificate_type
     *
     * @return the value of tcomm_customer.certificate_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.certificate_type
     *
     * @param certificateType the value for tcomm_customer.certificate_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType == null ? null : certificateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.certificate_no
     *
     * @return the value of tcomm_customer.certificate_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.certificate_no
     *
     * @param certificateNo the value for tcomm_customer.certificate_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo == null ? null : certificateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_name
     *
     * @return the value of tcomm_customer.cust_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_name
     *
     * @param custName the value for tcomm_customer.cust_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_no
     *
     * @return the value of tcomm_customer.cust_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_no
     *
     * @param custNo the value for tcomm_customer.cust_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_type
     *
     * @return the value of tcomm_customer.cust_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_type
     *
     * @param custType the value for tcomm_customer.cust_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_addr
     *
     * @return the value of tcomm_customer.cust_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustAddr() {
        return custAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_addr
     *
     * @param custAddr the value for tcomm_customer.cust_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustAddr(String custAddr) {
        this.custAddr = custAddr == null ? null : custAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.province_code
     *
     * @return the value of tcomm_customer.province_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.province_code
     *
     * @param provinceCode the value for tcomm_customer.province_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.province_name
     *
     * @return the value of tcomm_customer.province_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.province_name
     *
     * @param provinceName the value for tcomm_customer.province_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.eparchy_code
     *
     * @return the value of tcomm_customer.eparchy_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getEparchyCode() {
        return eparchyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.eparchy_code
     *
     * @param eparchyCode the value for tcomm_customer.eparchy_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setEparchyCode(String eparchyCode) {
        this.eparchyCode = eparchyCode == null ? null : eparchyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.eparchy_name
     *
     * @return the value of tcomm_customer.eparchy_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getEparchyName() {
        return eparchyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.eparchy_name
     *
     * @param eparchyName the value for tcomm_customer.eparchy_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setEparchyName(String eparchyName) {
        this.eparchyName = eparchyName == null ? null : eparchyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.area_code
     *
     * @return the value of tcomm_customer.area_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.area_code
     *
     * @param areaCode the value for tcomm_customer.area_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.area_name
     *
     * @return the value of tcomm_customer.area_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.area_name
     *
     * @param areaName the value for tcomm_customer.area_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.city_id
     *
     * @return the value of tcomm_customer.city_id
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.city_id
     *
     * @param cityId the value for tcomm_customer.city_id
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.city
     *
     * @return the value of tcomm_customer.city
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.city
     *
     * @param city the value for tcomm_customer.city
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.org
     *
     * @return the value of tcomm_customer.org
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public Integer getOrg() {
        return org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.org
     *
     * @param org the value for tcomm_customer.org
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setOrg(Integer org) {
        this.org = org;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_contact
     *
     * @return the value of tcomm_customer.cust_contact
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustContact() {
        return custContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_contact
     *
     * @param custContact the value for tcomm_customer.cust_contact
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustContact(String custContact) {
        this.custContact = custContact == null ? null : custContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.contact_tel
     *
     * @return the value of tcomm_customer.contact_tel
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.contact_tel
     *
     * @param contactTel the value for tcomm_customer.contact_tel
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.contact_addr
     *
     * @return the value of tcomm_customer.contact_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getContactAddr() {
        return contactAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.contact_addr
     *
     * @param contactAddr the value for tcomm_customer.contact_addr
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setContactAddr(String contactAddr) {
        this.contactAddr = contactAddr == null ? null : contactAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_manager
     *
     * @return the value of tcomm_customer.cust_manager
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustManager() {
        return custManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_manager
     *
     * @param custManager the value for tcomm_customer.cust_manager
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustManager(String custManager) {
        this.custManager = custManager == null ? null : custManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.create_time
     *
     * @return the value of tcomm_customer.create_time
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.create_time
     *
     * @param createTime the value for tcomm_customer.create_time
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.creator
     *
     * @return the value of tcomm_customer.creator
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.creator
     *
     * @param creator the value for tcomm_customer.creator
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.memo_
     *
     * @return the value of tcomm_customer.memo_
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.memo_
     *
     * @param memo the value for tcomm_customer.memo_
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.staff_size
     *
     * @return the value of tcomm_customer.staff_size
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getStaffSize() {
        return staffSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.staff_size
     *
     * @param staffSize the value for tcomm_customer.staff_size
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setStaffSize(String staffSize) {
        this.staffSize = staffSize == null ? null : staffSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_size
     *
     * @return the value of tcomm_customer.cust_size
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustSize() {
        return custSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_size
     *
     * @param custSize the value for tcomm_customer.cust_size
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustSize(String custSize) {
        this.custSize = custSize == null ? null : custSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_class_type
     *
     * @return the value of tcomm_customer.cust_class_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustClassType() {
        return custClassType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_class_type
     *
     * @param custClassType the value for tcomm_customer.cust_class_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustClassType(String custClassType) {
        this.custClassType = custClassType == null ? null : custClassType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_class_type_desc
     *
     * @return the value of tcomm_customer.cust_class_type_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustClassTypeDesc() {
        return custClassTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_class_type_desc
     *
     * @param custClassTypeDesc the value for tcomm_customer.cust_class_type_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustClassTypeDesc(String custClassTypeDesc) {
        this.custClassTypeDesc = custClassTypeDesc == null ? null : custClassTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_level
     *
     * @return the value of tcomm_customer.cust_level
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_level
     *
     * @param custLevel the value for tcomm_customer.cust_level
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustLevel(String custLevel) {
        this.custLevel = custLevel == null ? null : custLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_level_desc
     *
     * @return the value of tcomm_customer.cust_level_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustLevelDesc() {
        return custLevelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_level_desc
     *
     * @param custLevelDesc the value for tcomm_customer.cust_level_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustLevelDesc(String custLevelDesc) {
        this.custLevelDesc = custLevelDesc == null ? null : custLevelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_state
     *
     * @return the value of tcomm_customer.cust_state
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustState() {
        return custState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_state
     *
     * @param custState the value for tcomm_customer.cust_state
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustState(String custState) {
        this.custState = custState == null ? null : custState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_manager_code
     *
     * @return the value of tcomm_customer.cust_manager_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustManagerCode() {
        return custManagerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_manager_code
     *
     * @param custManagerCode the value for tcomm_customer.cust_manager_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustManagerCode(String custManagerCode) {
        this.custManagerCode = custManagerCode == null ? null : custManagerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_manager_no
     *
     * @return the value of tcomm_customer.cust_manager_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustManagerNo() {
        return custManagerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_manager_no
     *
     * @param custManagerNo the value for tcomm_customer.cust_manager_no
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustManagerNo(String custManagerNo) {
        this.custManagerNo = custManagerNo == null ? null : custManagerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_manager_name
     *
     * @return the value of tcomm_customer.cust_manager_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustManagerName() {
        return custManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_manager_name
     *
     * @param custManagerName the value for tcomm_customer.cust_manager_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustManagerName(String custManagerName) {
        this.custManagerName = custManagerName == null ? null : custManagerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.cust_namager_tel
     *
     * @return the value of tcomm_customer.cust_namager_tel
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getCustNamagerTel() {
        return custNamagerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.cust_namager_tel
     *
     * @param custNamagerTel the value for tcomm_customer.cust_namager_tel
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setCustNamagerTel(String custNamagerTel) {
        this.custNamagerTel = custNamagerTel == null ? null : custNamagerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.frist_pv_calling_type
     *
     * @return the value of tcomm_customer.frist_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getFristPvCallingType() {
        return fristPvCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.frist_pv_calling_type
     *
     * @param fristPvCallingType the value for tcomm_customer.frist_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setFristPvCallingType(String fristPvCallingType) {
        this.fristPvCallingType = fristPvCallingType == null ? null : fristPvCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.frist_pv_calling_type_name
     *
     * @return the value of tcomm_customer.frist_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getFristPvCallingTypeName() {
        return fristPvCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.frist_pv_calling_type_name
     *
     * @param fristPvCallingTypeName the value for tcomm_customer.frist_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setFristPvCallingTypeName(String fristPvCallingTypeName) {
        this.fristPvCallingTypeName = fristPvCallingTypeName == null ? null : fristPvCallingTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.second_pv_calling_type
     *
     * @return the value of tcomm_customer.second_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getSecondPvCallingType() {
        return secondPvCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.second_pv_calling_type
     *
     * @param secondPvCallingType the value for tcomm_customer.second_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setSecondPvCallingType(String secondPvCallingType) {
        this.secondPvCallingType = secondPvCallingType == null ? null : secondPvCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.second_pv_calling_type_name
     *
     * @return the value of tcomm_customer.second_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getSecondPvCallingTypeName() {
        return secondPvCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.second_pv_calling_type_name
     *
     * @param secondPvCallingTypeName the value for tcomm_customer.second_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setSecondPvCallingTypeName(String secondPvCallingTypeName) {
        this.secondPvCallingTypeName = secondPvCallingTypeName == null ? null : secondPvCallingTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.third_pv_calling_type
     *
     * @return the value of tcomm_customer.third_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getThirdPvCallingType() {
        return thirdPvCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.third_pv_calling_type
     *
     * @param thirdPvCallingType the value for tcomm_customer.third_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setThirdPvCallingType(String thirdPvCallingType) {
        this.thirdPvCallingType = thirdPvCallingType == null ? null : thirdPvCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.third_pv_calling_type_name
     *
     * @return the value of tcomm_customer.third_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getThirdPvCallingTypeName() {
        return thirdPvCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.third_pv_calling_type_name
     *
     * @param thirdPvCallingTypeName the value for tcomm_customer.third_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setThirdPvCallingTypeName(String thirdPvCallingTypeName) {
        this.thirdPvCallingTypeName = thirdPvCallingTypeName == null ? null : thirdPvCallingTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.four_pv_calling_type
     *
     * @return the value of tcomm_customer.four_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getFourPvCallingType() {
        return fourPvCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.four_pv_calling_type
     *
     * @param fourPvCallingType the value for tcomm_customer.four_pv_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setFourPvCallingType(String fourPvCallingType) {
        this.fourPvCallingType = fourPvCallingType == null ? null : fourPvCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.four_pv_calling_type_name
     *
     * @return the value of tcomm_customer.four_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getFourPvCallingTypeName() {
        return fourPvCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.four_pv_calling_type_name
     *
     * @param fourPvCallingTypeName the value for tcomm_customer.four_pv_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setFourPvCallingTypeName(String fourPvCallingTypeName) {
        this.fourPvCallingTypeName = fourPvCallingTypeName == null ? null : fourPvCallingTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.develop_flag
     *
     * @return the value of tcomm_customer.develop_flag
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getDevelopFlag() {
        return developFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.develop_flag
     *
     * @param developFlag the value for tcomm_customer.develop_flag
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setDevelopFlag(String developFlag) {
        this.developFlag = developFlag == null ? null : developFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.develop_flag_desc
     *
     * @return the value of tcomm_customer.develop_flag_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getDevelopFlagDesc() {
        return developFlagDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.develop_flag_desc
     *
     * @param developFlagDesc the value for tcomm_customer.develop_flag_desc
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setDevelopFlagDesc(String developFlagDesc) {
        this.developFlagDesc = developFlagDesc == null ? null : developFlagDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.department_code
     *
     * @return the value of tcomm_customer.department_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.department_code
     *
     * @param departmentCode the value for tcomm_customer.department_code
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.department_name
     *
     * @return the value of tcomm_customer.department_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.department_name
     *
     * @param departmentName the value for tcomm_customer.department_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.frist_calling_type
     *
     * @return the value of tcomm_customer.frist_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getFristCallingType() {
        return fristCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.frist_calling_type
     *
     * @param fristCallingType the value for tcomm_customer.frist_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setFristCallingType(String fristCallingType) {
        this.fristCallingType = fristCallingType == null ? null : fristCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.frist_calling_type_name
     *
     * @return the value of tcomm_customer.frist_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getFristCallingTypeName() {
        return fristCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.frist_calling_type_name
     *
     * @param fristCallingTypeName the value for tcomm_customer.frist_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setFristCallingTypeName(String fristCallingTypeName) {
        this.fristCallingTypeName = fristCallingTypeName == null ? null : fristCallingTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.second_calling_type
     *
     * @return the value of tcomm_customer.second_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getSecondCallingType() {
        return secondCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.second_calling_type
     *
     * @param secondCallingType the value for tcomm_customer.second_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setSecondCallingType(String secondCallingType) {
        this.secondCallingType = secondCallingType == null ? null : secondCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.second_calling_type_name
     *
     * @return the value of tcomm_customer.second_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getSecondCallingTypeName() {
        return secondCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.second_calling_type_name
     *
     * @param secondCallingTypeName the value for tcomm_customer.second_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setSecondCallingTypeName(String secondCallingTypeName) {
        this.secondCallingTypeName = secondCallingTypeName == null ? null : secondCallingTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.third_calling_type
     *
     * @return the value of tcomm_customer.third_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getThirdCallingType() {
        return thirdCallingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.third_calling_type
     *
     * @param thirdCallingType the value for tcomm_customer.third_calling_type
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setThirdCallingType(String thirdCallingType) {
        this.thirdCallingType = thirdCallingType == null ? null : thirdCallingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcomm_customer.third_calling_type_name
     *
     * @return the value of tcomm_customer.third_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public String getThirdCallingTypeName() {
        return thirdCallingTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcomm_customer.third_calling_type_name
     *
     * @param thirdCallingTypeName the value for tcomm_customer.third_calling_type_name
     *
     * @mbggenerated Fri Mar 06 10:01:27 CST 2020
     */
    public void setThirdCallingTypeName(String thirdCallingTypeName) {
        this.thirdCallingTypeName = thirdCallingTypeName == null ? null : thirdCallingTypeName.trim();
    }
}