package com.example.user.dao;

import com.example.api.entity.Test1;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface Test1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_1
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_1
     *
     * @mbggenerated
     */
    int insert(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_1
     *
     * @mbggenerated
     */
    Test1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_1
     *
     * @mbggenerated
     */
    List<Test1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_1
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Test1 record);
}