package com.example.user.dao;

import com.example.user.entity.TVericode;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface TVericodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    int insert(TVericode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    TVericode selectByPrimaryKey(Integer codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    List<TVericode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TVericode record);
}