package com.example.user.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class StartUserFeeInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_user_fee_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_user_fee_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column start_user_fee_info.user_fee
     *
     * @mbggenerated
     */
    private BigDecimal userFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table start_user_fee_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_user_fee_info.id
     *
     * @return the value of start_user_fee_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_user_fee_info.id
     *
     * @param id the value for start_user_fee_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_user_fee_info.user_id
     *
     * @return the value of start_user_fee_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_user_fee_info.user_id
     *
     * @param userId the value for start_user_fee_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column start_user_fee_info.user_fee
     *
     * @return the value of start_user_fee_info.user_fee
     *
     * @mbggenerated
     */
    public BigDecimal getUserFee() {
        return userFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column start_user_fee_info.user_fee
     *
     * @param userFee the value for start_user_fee_info.user_fee
     *
     * @mbggenerated
     */
    public void setUserFee(BigDecimal userFee) {
        this.userFee = userFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table start_user_fee_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userFee=").append(userFee);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}