package com.example.user.entity;

import java.io.Serializable;
import java.util.Date;

public class TVericode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vericode.code_id
     *
     * @mbggenerated
     */
    private Integer codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vericode.code_number
     *
     * @mbggenerated
     */
    private String codeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vericode.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vericode.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vericode.code_id
     *
     * @return the value of t_vericode.code_id
     *
     * @mbggenerated
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vericode.code_id
     *
     * @param codeId the value for t_vericode.code_id
     *
     * @mbggenerated
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vericode.code_number
     *
     * @return the value of t_vericode.code_number
     *
     * @mbggenerated
     */
    public String getCodeNumber() {
        return codeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vericode.code_number
     *
     * @param codeNumber the value for t_vericode.code_number
     *
     * @mbggenerated
     */
    public void setCodeNumber(String codeNumber) {
        this.codeNumber = codeNumber == null ? null : codeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vericode.phone_number
     *
     * @return the value of t_vericode.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vericode.phone_number
     *
     * @param phoneNumber the value for t_vericode.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vericode.create_time
     *
     * @return the value of t_vericode.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vericode.create_time
     *
     * @param createTime the value for t_vericode.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vericode
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", codeId=").append(codeId);
        sb.append(", codeNumber=").append(codeNumber);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}